Repository Flyinchicken/Comp-354-Team-N, pull requests merged in 2023-04, with the labels that each got.

#12 Closes Demo/UI-V2 : Added dark theme and changed button UI
  src/html/index.html
  src/style/style.js
Labels: enhancement

#25 Added a new display area for the current calculation result
  src/html/index.html
  src/js/stnd/main.js
  src/style/style.css
Labels: enhancement, UI

#33 Dark theme added for Precision
  src/html/index.html
  src/js/stnd/main.js
  src/js/stnd/style.js
Labels: bug, enhancement

#34 Changed log function to use MathML
  src/html/index.html
Labels: enhancement

#35 Responsive Navbar
  src/html/index.html
Labels: enhancement
